
APPLICATION_NAME = 'qBittorrenTUI'

DAEMON_LOOP_INTERVAL = 2  # seconds
TIME_AFTER_CONN_FAILURE_THAT_CONNECTION_IS_CONSIDERED_LOST = 5  # seconds

MAX_TORRENT_CONTENT_FILENAME_WIDTH = 75

MAX_TORRENT_LIST_TORRENT_NAME_LENGTH = 85
TORRENT_LIST_PROGRESS_BAR_LENGTH = 40

STATE_MAP_FOR_DISPLAY = {'pausedUP': 'Completed',
                         'uploading': 'Seeding',
                         'stalledUP': 'Seeding',
                         'forcedUP': '[F] Seeding',
                         'queuedDL': 'Queued',
                         'queuedUP': 'Queued',
                         'pausedDL': 'Paused',
                         'checkingDL': 'Checking',
                         'checkingUP': 'Checking',
                         'downloading': 'Downloading',
                         'forcedDL': '[F] Downloading',
                         'metaDL': 'Downloading',
                         'stalledDL': 'Stalled',
                         'allocating': 'Allocating',
                         'moving': 'Moving',
                         'missingfiles': 'Missing Files',
                         'error': 'Error',
                         'queuedForChecking': 'Queued for Checking',
                         'checkingResumeData': 'Checking Resume Data'}
TORRENT_LIST_FILTERING_STATE_MAP = {'downloading': ['downloading',
                                                       'metaDL',
                                                       'queuedDL',
                                                       'stalledDL',
                                                       'pausedDL',
                                                       'forcedDL'
                                                       ],
                                       'completed': ['uploading',
                                                     'stalledUP',
                                                     'checkingUP',
                                                     'pausedUP',
                                                     'queuedUP',
                                                     'forcedUP',
                                                     ],
                                       'active': ['metaDL',
                                                  'downloading',
                                                  'forcedDL',
                                                  'uploading',
                                                  'forcedUP',
                                                  'moving',
                                                  ],
                                       'inactive': ['pausedUP',
                                                    'stalledUP',
                                                    'stalledDL',
                                                    'queuedDL',
                                                    'queuedUP',
                                                    'pausedDL',
                                                    'checkingDL',
                                                    'checkingUP',
                                                    'allocating',
                                                    'missingfiles',
                                                    'error',
                                                    'queuedForChecking',
                                                    'checkingResumeData',
                                                    ],
                                       'paused': ['pausedUP',
                                                  'queuedDL',
                                                  'queuedUP',
                                                  'pausedDL',
                                                  'missingfiles',
                                                  'error',
                                                  'queuedForChecking',
                                                  'checkingResumeData',
                                                  ],
                                       'resumed': ['uploading',
                                                   'stalledUP',
                                                   'forcedUP',
                                                   'checkingDL',
                                                   'checkingUP',
                                                   'downloading',
                                                   'forcedDL',
                                                   'metaDL',
                                                   'stalledDL',
                                                   'allocating',
                                                   'moving']
                                       }
