name: Upload Python Package

on:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # required for trusted publishing
    steps:
      - name: Fetch Package
        uses: dsaltares/fetch-gh-release-asset@1.1.1
        with:
          version: tags/${{ github.event.release.tag_name }}
          file: qbittorrentui*
          regex: true
          target: dist/

      - name: Publish release to production PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
